---
- name: Configure & Install syslog to send logs to Graylog Server
  hosts: all
  become: yes
  vars:
    graylog_server_ip: "44.31.255.69"
  tasks:
    - name: Ensure rsyslog is installed
      apt:
        name: rsyslog
        state: present
        update_cache: yes

    - name: Configure rsyslog to forward logs to Graylog
      lineinfile:
        path: /etc/rsyslog.conf
        line: "*.* @{{ graylog_server_ip }}:514"
        state: present

    - name: Restart rsyslog service
      systemd:
        name: rsyslog
        state: restarted
        enabled: yes
