all:
  hosts:
    44.31.255.24:
  vars:
    ansible_user: root
    ansible_password: password

  children:
    syslog_clients:
      hosts:
        44.31.255.60:
        44.31.255.61:
        44.31.255.62:
        44.31.255.63:
        44.31.255.64:
        44.31.255.65:
        44.31.255.66:
